# Project information
site_name: RNA localization in c. elegans
site_description: An ImJoy plugin to quantify RNA localization patterns
site_author: Florian MUELLER
site_url: https://muellerflorian.github.io/parker-rna-loc-elegans/

# Repository
repo_name: GitHub
repo_url: https://github.com/muellerflorian/parker-rna-loc-elegans.git
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2019 Florian MUELLER'

# Configuration
theme:
  name: 'material'
  #name: mkdocs
  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: img/icons8-earth-worm-80.png
  logo: img/icons8-earth-worm-80.png

# Customization
extra:
  social:
    - type: github-alt
      link: https://github.com/muellerflorian
    - type: linkedin
      link: https://www.linkedin.com/in/muellerflorian/
    - type: google
      link: https://scholar.google.fr/citations?user=WrEj9t4AAAAJ

# MD extension
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.tilde

nav:
    - Overview: index.md   # Needed for material theme but not for others
    - Analysis tools: tools.md  # This is strange but onlywith this organization this file shows upd in the overview together with the index.md
    - RNA localization:
      - Cell membrane distance: cell-membrane-dist.md
      - Nuclear envelope distance: nuc-envelop-dist.md
      - Granule co-localization: granules-coloc.md
    - General workflows:
      - Image processing: image-processing.md
      - RNA detection: rna-detection.md
    - About:
      - Release Notes: release-notes.md
      - Licence: licence.md


#theme:
#  name: 'material'
