---
title: "191027_plot_Figure2A"
author: "Erin Nishimura"
date: "10/27/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

### Load libraries: 

dplyr, ggplots, gridExtra
```{r, echo = FALSE, warning = FALSE}
print("script initiated on", quote = FALSE)
Sys.time()

#loading packages
library(dplyr)
library(ggplot2)
library(gridExtra)

```


### Import the data

Import "figure2_sourcedata1_191027.txt"
```{r setup, echo = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)

##This is for datasource generation
# import the data
#erm1HistTable <- read.table(file = "../1_input/figure2_sourcedata1_191027.csv", header = TRUE, sep = ";") 
#set3HistTable <- read.table(file = "../1_input/HistogramPooled_set3_Fig2A.csv", header = TRUE, sep = ";") 

#erm1HistTable <- erm1HistTable %>%
#  mutate(probe = "erm-1")

#set3HistTable <- set3HistTable %>%
#  mutate(probe = "set-3")

#fullHistTable <- rbind(erm1HistTable, set3HistTable)

#fullHistTable
#write.table(fullHistTable, file = "../1_input/figure2_sourcedata1_191027.txt", quote = FALSE, sep = "\t")

HistTable <- read.table(file = "../1_input/figure2_sourcedata1_191027.txt", header = TRUE)
```

### Plot the barplots of _erm-1_ and _set-3_

Draw barplots of each


```{r, echo = FALSE, warning = FALSE}

# set colors
colors = c(
  "#000000FF",
  "#330000FF",
  "#660000FF",
  "#CC3333FF",
  "#FF3333FF",
  "#FF9933FF",
  "#FFCC66FF",
  "#FFFF00FF",
  "#FFFF99FF")

# filter data for erm-1
erm1HistTable <- HistTable %>%
  filter(probe == "erm-1")

par(mar = c(5.1, 5.1, 4.1, 2.1))

barplot(erm1HistTable$hist_RNA_all_normPix,
        names.arg = erm1HistTable$center,
        border = NA,
        space = 0.1,
        col = colors,
        family = "sans",
        xlab = "Distance from cortex [pixel]", 
        ylab = "erm-1 mRNA\n[norm. frequency]", 
        ylim = c(0, 2.0))

# filter data for set-3 
set3HistTable <- HistTable %>%
  filter(probe == "set-3")

barplot(set3HistTable$hist_RNA_all_normPix,
        names.arg = set3HistTable$center,
        border = NA,
        space = 0.1,
        col = colors,
        family = "sans",
        xlab = "Distance from cortex [pixel]", 
        ylab = "set-3 mRNA\n[norm. frequency]", 
        ylim = c(0, 2.0))




# output plot
#Set date
date <- format(Sys.time(), "%y%m%d")
#set filename
filename <- paste("../3_output/", date, "_output_plots_Fig2a.pdf", sep = "")
filename

pdf(file = filename, width = 8, height = 4)
par(mfrow = c(1,2))
par(mar = c(5.1, 5.1, 4.1, 2.1))

barplot(erm1HistTable$hist_RNA_all_normPix,
        names.arg = erm1HistTable$center,
        border = NA,
        space = 0.1,
        col = colors,
        family = "sans",
        xlab = "Distance from cortex [pixel]", 
        ylab = "erm-1 mRNA\n[norm. frequency]", 
        ylim = c(0, 2.0))

barplot(set3HistTable$hist_RNA_all_normPix,
        names.arg = set3HistTable$center,
        border = NA,
        space = 0.1,
        col = colors,
        family = "sans",
        xlab = "Distance from cortex [pixel]", 
        ylab = "set-3 mRNA\n[norm. frequency]", 
        ylim = c(0, 2.0))
  
dev.off()
dev.off()

#Report
print("The following output plot was saved: ", quote = FALSE)
print(filename, quote = FALSE)

```

### Get versions
```{r, echo = TRUE}
sessionInfo()
```

