---
title: "200326_plot_Figure2B"
author: "Erin Nishimura"
date: "03/26/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

### Load libraries: 

dplyr, ggplots
```{r, echo = FALSE, warning = FALSE}
print("script initiated on", quote = FALSE)
Sys.time()

#loading packages
library(dplyr)
library(ggplot2)

```


### Import the data

Import "figure2_sourcedata2_200326.txt"
```{r setup, echo = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# ##This is for datasource generation
# # import the data
# imb2HistTable <- read.table(file = "../1_input/imb-2_quant_fig-2b.csv", header = TRUE, sep = ",") 
# set3HistTable <- read.table(file = "../1_input/set-3_quant_fig-2b.csv", header = TRUE, sep = ",") 
# 
# imb2HistTable <- imb2HistTable[1:(dim(set3HistTable)[1] -1),] %>%
#   mutate(probe = "imb-2")
# 
# set3HistTable <- set3HistTable[1:(dim(set3HistTable)[1] -1),] %>%
#   mutate(probe = "set-3")
# 
# fullHistTable <- rbind(imb2HistTable, set3HistTable)
# 
# fullHistTable
# write.table(fullHistTable, file = "../1_input/figure2_sourcedata2_191028.txt", quote = FALSE, sep = "\t")

HistTable <- read.table(file = "../1_input/figure2_sourcedata2_200326.txt", header = TRUE)
help(read.table)
```

### Plot the barplots of _imb-2_ and _set-3_

Draw barplots of each


```{r, echo = FALSE, warning = FALSE}

#HistTable

par(mfrow = c(2,1))

# filter data for imb-2
imb2HistTable <- HistTable %>%
  filter(probe == "imb-2")

# set plot dimensions
par(mar = c(4.1, 4.1,2.1, 2.1))

# plot imb-2
barplot(imb2HistTable$histRNA_SCAL,
        names.arg = imb2HistTable$center,
        space = 0.1,
        border = NA,
        col = "grey",
        family = "sans",
        xlab = "Distance from nuclear periphery [pixel]", 
        ylab = "imb-2 mRNA\n[norm. frequency",
        ylim = c(0, 2.0))
box(lty = "solid", col = 'black')

# filter data for set-3 
set3HistTable <- HistTable %>%
  filter(probe == "set-3")

# plot set-3
barplot(set3HistTable$histRNA_SCALED,
        names.arg = set3HistTable$center,
        border = NA,
        space = 0.1,
        col = "grey",
        family = "sans",
        xlab = "Distance from nuclear periphery [pixel]", 
        ylab = "set-3 mRNA\n[norm. frequency]", 
        ylim = c(0, 2.0))
box(lty = "solid", col = 'black')

# output plot
#Set date
date <- format(Sys.time(), "%y%m%d")
#set filename
filename <- paste("../3_output/", date, "_output_plots_Fig2b.pdf", sep = "")
filename

pdf(file = filename, width = 4, height = 4)
par(mfrow = c(2,1))
par(mar = c(4.1, 4.1,2.1, 2.1))

# plot imb-2
barplot(imb2HistTable$histRNA_SCAL,
        names.arg = imb2HistTable$center,
        space = 0.1,
        border = NA,
        col = "grey",
        family = "sans",
        xlab = "Distance from cortex [pixel]", 
        ylab = "imb-2 mRNA\n[norm. frequency",
        ylim = c(0, 2.0))
box(lty = "solid", col = 'black')

# plot set-3
barplot(set3HistTable$histRNA_SCALED,
        names.arg = set3HistTable$center,
        border = NA,
        space = 0.1,
        col = "grey",
        family = "sans",
        xlab = "Distance from cortex [pixel]", 
        ylab = "set-3 mRNA\n[norm. frequency]", 
        ylim = c(0, 2.0))
box(lty = "solid", col = 'black')
  
dev.off()
dev.off()

#Report
print("The following output plot was saved: ", quote = FALSE)
print(filename, quote = FALSE)

```

### Get versions
```{r, echo = TRUE}
sessionInfo()
```

